// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpfgsjqwgmazgbmmbrkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwZmdzanF3Z21hemdibW1icmtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMzMxNDEsImV4cCI6MjA2NzgwOTE0MX0.FvvKQBpLEom3k2WzESc-P9PKKh5el0ZWwLqqV3UxfdA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});